setup for filling in menu items
FuelLabs/swayswap-demo pull request #9
Opened 2022-02-19 20:38 UTC by eureka-cpu

removed hard coded coins and setup the menu to accept the json file

2022-02-19 21:10 UTC, eureka-cpu commented
Forgot to remove headless ui from just dependencies package.json

2022-02-22 22:22 UTC, adlerjohn commented
Is this ready for review?

2022-02-22 23:23 UTC, eureka-cpu commented
@headless-ui needs to be removed from the package.json, but yes

2022-03-02 15:15 UTC, adlerjohn reviewed
Looks reasonable, will defer to @luizstacio as the JS expert 😂

2022-03-02 15:40 UTC, luizstacio requested changes
One review, other than that is good! Nice work, looking forward to start refactoring

2022-03-02 15:40 UTC, luizstacio commented on client/components/Assets.tsx
> +const coinList = require('../lib/assets.json');
Prefer use of `import`

2022-03-03 15:52 UTC, merged